# Generated by Django 5.0.13 on 2025-03-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=255)),
                ('step_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=255)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='step_stage.step')),
            ],
        ),
    ]
