# Generated by Django 5.0.13 on 2025-03-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=255)),
                ('start_stage_id', models.IntegerField()),
                ('end_stage_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('appointment_date', models.DateTimeField()),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.degree')),
            ],
        ),
    ]
