# Generated by Django 5.0.13 on 2025-03-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuingAuthority',
            fields=[
                ('issuing_authority_id', models.AutoField(primary_key=True, serialize=False)),
                ('issuing_authority_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('promotion_date', models.DateTimeField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionOrder',
            fields=[
                ('promotion_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('promotion_order_no', models.CharField(max_length=255)),
                ('promotion_order_date', models.DateTimeField()),
                ('promotion_value', models.IntegerField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('issuing_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuing_authority', to='promos.issuingauthority')),
            ],
        ),
        migrations.CreateModel(
            name='SanctionOrder',
            fields=[
                ('sanction_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('sanction_order_no', models.CharField(max_length=255)),
                ('sanction_order_date', models.DateTimeField()),
                ('sanction_value', models.IntegerField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('issuing_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promos.issuingauthority')),
            ],
        ),
    ]
